# Site settings
title: 中美青年创客大赛
subTitle: China-US Young Maker Competition
description: 2018成都分赛区
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 西南交通大学创客空间 <br/>中美青年创客交流中心
user_description: ？
user_title: ？
email: anon@anon.com
twitter_username: 西南交通大学创客空间
github_username:  西南交通大学创客空间
gplus_username:  西南交通大学创客空间

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
